import Link from 'next/link'

export const metadata = { title: 'Terms of Service — FORTIS OS', description: 'FORTIS OS Terms of Service. Read before using the platform.' }

const G = '#1B4D3E'
const GOLD = '#C4943A'
const LAST_UPDATED = '24 August 2026'

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: "'DM Sans', system-ui, sans-serif" }}>

      <div style={{ background: `linear-gradient(135deg, #0A2E1A, ${G})`, padding: '3rem 1.5rem 2.5rem', borderBottom: `2px solid ${GOLD}40` }}>
        <div style={{ maxWidth: 860, margin: '0 auto' }}>
          <div style={{ display: 'inline-block', background: `${GOLD}20`, border: `1px solid ${GOLD}50`, borderRadius: 999, padding: '4px 14px', fontSize: '0.72rem', fontWeight: 700, color: GOLD, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 16 }}>
            Legal Document
          </div>
          <h1 style={{ margin: '0 0 10px', fontSize: 'clamp(1.6rem, 3vw, 2.2rem)', fontWeight: 900, color: '#fff' }}>Terms of Service</h1>
          <p style={{ margin: 0, color: 'rgba(255,255,255,0.7)', fontSize: '0.9rem' }}>
            Last updated: {LAST_UPDATED} · Governing law: The Gambia + England & Wales
          </p>
        </div>
      </div>

      <div style={{ maxWidth: 860, margin: '0 auto', padding: '3rem 1.5rem' }}>

        <div style={{ background: '#FEF3C7', border: '1px solid #D97706', borderRadius: 10, padding: '1rem 1.25rem', marginBottom: '2.5rem', fontSize: '0.85rem', color: '#92400E' }}>
          <strong>⚠️ Important:</strong> By using FORTIS OS, you agree to these Terms. If you do not agree, do not use the platform. These terms constitute a legally binding agreement between you and UJU GROUP LIMITED.
        </div>

        <Section title="1. Definitions">
          <ul>
            <li><strong>"Platform"</strong> — FORTIS OS™ at https://fortisos.cloud and all subdomains</li>
            <li><strong>"We / Us / Company"</strong> — UJU GROUP LIMITED (England & Wales) operating through FORTIS INVICTA LTD</li>
            <li><strong>"You / User"</strong> — any individual or entity accessing the Platform</li>
            <li><strong>"AI Tools"</strong> — UJU Cycle™, IKENGA™, ASK UJRIS™ and all other AI-powered features</li>
            <li><strong>"Output"</strong> — any analysis, report, score, or recommendation generated by the AI Tools</li>
            <li><strong>"Business Data"</strong> — any information you submit about yourself or your business</li>
          </ul>
        </Section>

        <Section title="2. Platform Status & Beta Disclaimer">
          <div style={{ background: '#EFF6FF', border: '1px solid #3B82F6', borderRadius: 8, padding: '1rem', marginBottom: 12, fontSize: '0.85rem' }}>
            <strong>🔵 Beta Platform Notice:</strong> FORTIS OS is in active development. Some modules are in beta or pilot stage. We clearly indicate this where applicable. Features may change without notice.
          </div>
          <p>The following modules are in <strong>Beta / Pilot</strong> status as of {LAST_UPDATED}:</p>
          <ul>
            <li>Credit scoring — refused (HTTP 503). Not a lending product.</li>
            <li>Carbon Credit Origination — specification phase</li>
            <li>Master Dashboard — internal operations use</li>
            <li>ISO 27001 certification — currently being pursued (target Q4 2026)</li>
          </ul>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You may use FORTIS OS to:</p>
          <ul>
            <li>Analyse your own business using UJU Cycle™</li>
            <li>Generate brand content using IKENGA™</li>
            <li>Analyse documents you have the right to analyse using ASK UJRIS™</li>
            <li>Access public data resources, maps, and knowledge hub content</li>
            <li>Enrol in and complete training courses</li>
          </ul>
          <p>You may <strong>not</strong>:</p>
          <ul>
            <li>Reverse-engineer, scrape, or systematically extract platform data</li>
            <li>Use AI Tools to generate fraudulent, misleading, or harmful content</li>
            <li>Submit documents belonging to third parties without authorisation</li>
            <li>Attempt to circumvent security controls or authentication</li>
            <li>Use the platform in violation of Gambia Cybercrime Act 2021 or UK Computer Misuse Act 1990</li>
            <li>Resell or white-label platform outputs without a commercial licence</li>
          </ul>
        </Section>

        <Section title="4. AI Output Disclaimer — Critical">
          <div style={{ background: '#FFF1F2', border: '1px solid #E11D48', borderRadius: 8, padding: '1rem', marginBottom: 12, fontSize: '0.85rem', color: '#881337' }}>
            <strong>⚠️ AI outputs are not professional advice.</strong>
          </div>
          <ul>
            <li><strong>UJU Cycle™ outputs</strong> are diagnostic tools only. They do not constitute accounting, financial, or management consulting advice.</li>
            <li><strong>IKENGA™ outputs</strong> are content suggestions. Brand positioning decisions should involve qualified marketing professionals.</li>
            <li><strong>ASK UJRIS™ outputs</strong> are analytical indicators only. They do not constitute legal advice. Do not sign, reject, or litigate a contract solely on the basis of UJRIS output. Consult a qualified lawyer.</li>
            <li><strong>Credit scores</strong> are advisory. Final lending decisions rest with the financial institution. FORTIS OS bears no liability for credit decisions made using our scoring engine.</li>
            <li>All outputs carry uncertainty. Confidence intervals are shown where available. Low-confidence outputs are flagged.</li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          <p>All content, software, AI models, training data, and proprietary algorithms on FORTIS OS are owned by UJU GROUP LIMITED and protected under:</p>
          <ul>
            <li>Gambia Copyright Act 2004</li>
            <li>Gambia Cybercrime Act 2021</li>
            <li>UK Copyright, Designs and Patents Act 1988</li>
          </ul>
          <p><strong>Trademarks:</strong> FORTIS OS™, IKENGA™, UJU Cycle™, ASK UJRIS™, UJU GROUP™ are trademarks of UJU GROUP LIMITED. Unauthorised use is prohibited.</p>
          <p><strong>Your content:</strong> You retain ownership of Business Data you submit. You grant us a limited licence to process it for the purpose of delivering the AI Tools.</p>
        </Section>

        <Section title="6. Subscription & Payment">
          <p>Access tiers and pricing are published at <Link href="/pricing" style={{ color: G }}>/pricing</Link>. Key terms:</p>
          <ul>
            <li>Free tier: unlimited access to public resources, knowledge hub, and training</li>
            <li>Standard tier: AI tool access with monthly/annual billing</li>
            <li>Enterprise/API tier: institutional access with custom SLA — contact <a href="mailto:enterprise@fortisos.gm" style={{ color: G }}>enterprise@fortisos.gm</a></li>
            <li>Paid SKUs use bank/wallet transfer (GMD catalogue). Live card capture is off. FORTIS is not a licensed PSP.</li>
            <li>Refunds: within 14 days of first payment if AI tools produce no usable output</li>
          </ul>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>To the maximum extent permitted by law:</p>
          <ul>
            <li>We are not liable for business decisions made based on AI Tool outputs</li>
            <li>We are not liable for losses arising from platform downtime or service interruption</li>
            <li>Our total liability in any 12-month period is capped at the fees you paid us in that period</li>
            <li>We are not liable for indirect, consequential, or special damages</li>
          </ul>
        </Section>

        <Section title="8. Governing Law & Disputes">
          <p>These Terms are governed by the laws of <strong>The Gambia</strong> and, for UK users, the laws of <strong>England & Wales</strong>.</p>
          <p>Disputes will first be addressed through good-faith negotiation (30 days). If unresolved:</p>
          <ul>
            <li>Gambia users: Gambia courts have jurisdiction</li>
            <li>UK users: English courts have jurisdiction</li>
            <li>International users: Arbitration under ICC rules, seat in London</li>
          </ul>
        </Section>

        <Section title="9. Changes to Terms">
          <p>We may update these Terms. We will notify registered users 30 days before material changes take effect. Continued use constitutes acceptance of revised Terms.</p>
        </Section>

        <Section title="10. Contact">
          <ul>
            <li><strong>Legal:</strong> <a href="mailto:legal@fortisos.gm" style={{ color: G }}>legal@fortisos.gm</a></li>
            <li><strong>Enterprise:</strong> <a href="mailto:enterprise@fortisos.gm" style={{ color: G }}>enterprise@fortisos.gm</a></li>
            <li><strong>Legal inquiries form:</strong> <Link href="/legal/inquiries" style={{ color: G }}>/legal/inquiries</Link></li>
          </ul>
        </Section>

        <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: '1.5rem', marginTop: '2rem', display: 'flex', flexWrap: 'wrap', gap: 16, alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ fontSize: '0.8rem', color: '#64748b' }}>© 2026 UJU GROUP LIMITED · FORTIS OS™</div>
          <div style={{ display: 'flex', gap: 16 }}>
            <Link href="/privacy" style={{ fontSize: '0.8rem', color: G }}>Privacy Policy</Link>
            <Link href="/compliance" style={{ fontSize: '0.8rem', color: G }}>Compliance Centre</Link>
          </div>
        </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '2.5rem' }}>
      <h2 style={{ fontSize: '1.05rem', fontWeight: 800, color: G, margin: '0 0 1rem', paddingBottom: 8, borderBottom: '2px solid #e2e8f0' }}>{title}</h2>
      <div style={{ fontSize: '0.9rem', color: '#374151', lineHeight: 1.75 }}>{children}</div>
    </div>
  )
}
