export interface DevelopmentPartner {
  id: string;
  name: string;
  acronym: string;
  type: "un_agency" | "multilateral_bank" | "bilateral_donor" | "regional_body" | "ingo" | "foundation";
  focusAreas: string[];
  address: string;
  area: string;
  lat: number;
  lng: number;
  website: string;
  phone?: string;
  email?: string;
  localRep?: string;
  fundingWindows?: string[];
  programmes?: string[];
  description?: string;
}

export const DEVELOPMENT_PARTNERS: DevelopmentPartner[] = [
  // ── UN Agencies ────────────────────────────────────────────────────────────
  {
    id: "undp-gambia",
    name: "United Nations Development Programme",
    acronym: "UNDP",
    type: "un_agency",
    focusAreas: ["Governance", "SDG Implementation", "Digital Transformation", "Justice", "Poverty Reduction"],
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4523,
    lng: -16.6792,
    website: "https://www.undp.org/gambia",
    phone: "+220 449 5555",
    email: "registry.gm@undp.org",
    localRep: "Country Director",
    fundingWindows: ["SDG Fund", "Governance and Peacebuilding", "Digital Transformation"],
    programmes: ["Governance and Rule of Law", "SDG Acceleration", "Youth Empowerment"],
    description: "UN's global development network focused on poverty reduction, democratic governance, and sustainable development.",
  },
  {
    id: "unicef-gambia",
    name: "United Nations Children's Fund",
    acronym: "UNICEF",
    type: "un_agency",
    focusAreas: ["Child Protection", "Education", "Health", "Social Policy", "Nutrition"],
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4525,
    lng: -16.6790,
    website: "https://www.unicef.org/gambia",
    phone: "+220 449 5454",
    email: "banjul@unicef.org",
    localRep: "Country Representative",
    programmes: ["Child Protection", "Quality Education", "Health and Nutrition", "Social Protection"],
    description: "UN agency providing humanitarian and developmental aid to children worldwide.",
  },
  {
    id: "wfp-gambia",
    name: "World Food Programme",
    acronym: "WFP",
    type: "un_agency",
    focusAreas: ["Food Security", "Nutrition", "Emergency Response", "Supply Chain"],
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4524,
    lng: -16.6793,
    website: "https://www.wfp.org/countries/gambia",
    phone: "+220 449 5353",
    email: "wfp.gambia@wfp.org",
    localRep: "Country Director",
    programmes: ["School Feeding", "Nutrition Support", "Emergency Food Assistance", "Resilience Building"],
    description: "World's largest humanitarian organization building pathways to peace through food assistance.",
  },
  {
    id: "who-gambia",
    name: "World Health Organization",
    acronym: "WHO",
    type: "un_agency",
    focusAreas: ["Public Health", "Health Systems", "Disease Prevention", "Pandemic Preparedness"],
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4520,
    lng: -16.6795,
    website: "https://www.afro.who.int/countries/gambia",
    phone: "+220 449 5656",
    email: "afwogm@who.int",
    localRep: "WHO Representative",
    programmes: ["Universal Health Coverage", "Health Security", "Non-Communicable Diseases", "Maternal and Child Health"],
    description: "UN agency responsible for international public health.",
  },
  {
    id: "fao-gambia",
    name: "Food and Agriculture Organization",
    acronym: "FAO",
    type: "un_agency",
    focusAreas: ["Agriculture", "Food Security", "Fisheries", "Climate Resilience"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5770,
    website: "https://www.fao.org/gambia",
    phone: "+220 422 5678",
    email: "fao-gm@fao.org",
    localRep: "FAO Representative",
    programmes: ["Agricultural Development", "Food Security", "Climate Smart Agriculture", "Fisheries Management"],
    description: "UN agency leading international efforts to defeat hunger and improve food security.",
  },
  {
    id: "iom-gambia",
    name: "International Organization for Migration",
    acronym: "IOM",
    type: "un_agency",
    focusAreas: ["Migration Management", "Border Management", "Assisted Voluntary Return", "Counter-Trafficking"],
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4522,
    lng: -16.6788,
    website: "https://www.iom.int/countries/gambia",
    phone: "+220 449 5455",
    email: "iombanjul@iom.int",
    localRep: "Chief of Mission",
    programmes: ["Migration Health", "Border Management", "Assisted Voluntary Return", "Community Stabilization"],
    description: "UN migration agency committed to humane and orderly migration for the benefit of all.",
  },
  {
    id: "unhcr-gambia",
    name: "UN High Commissioner for Refugees",
    acronym: "UNHCR",
    type: "un_agency",
    focusAreas: ["Refugee Protection", "Asylum Processing", "Statelessness", "Emergency Response"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4545,
    lng: -16.5775,
    website: "https://www.unhcr.org/gambia",
    phone: "+220 422 7890",
    email: "gmb@unhcr.org",
    localRep: "Country Representative",
    programmes: ["Refugee Protection", "Asylum Seekers Support", "Statelessness Reduction"],
    description: "UN agency mandated to protect and support refugees worldwide.",
  },
  {
    id: "unfpa-gambia",
    name: "United Nations Population Fund",
    acronym: "UNFPA",
    type: "un_agency",
    focusAreas: ["Reproductive Health", "Population Data", "Youth", "Gender Equality"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4542,
    lng: -16.5772,
    website: "https://www.unfpa.org/gambia",
    phone: "+220 422 4567",
    email: "gambia@unfpa.org",
    localRep: "Country Representative",
    programmes: ["Sexual and Reproductive Health", "Population and Development", "Youth Empowerment"],
    description: "UN sexual and reproductive health agency.",
  },
  {
    id: "un-women-gambia",
    name: "UN Women Gambia",
    acronym: "UN Women",
    type: "un_agency",
    focusAreas: ["Gender Equality", "Women's Empowerment", "Legal Rights", "Economic Empowerment"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://www.unwomen.org/gambia",
    email: "gambia@unwomen.org",
    programmes: ["Women's Leadership", "Economic Empowerment", "Ending Violence Against Women"],
    description: "UN entity for gender equality and women's empowerment.",
  },
  {
    id: "unido-gambia",
    name: "United Nations Industrial Development Organization",
    acronym: "UNIDO",
    type: "un_agency",
    focusAreas: ["Industrial Development", "SME Support", "Technology Transfer", "Agribusiness"],
    address: "Regional Office, Dakar",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.unido.org",
    email: "unido-dakar@unido.org",
    programmes: ["Agribusiness Development", "SME Competitiveness", "Technology Transfer"],
    description: "UN agency promoting industrial development for poverty reduction and sustainable development.",
  },
  {
    id: "unep-regional",
    name: "UN Environment Programme — West Africa",
    acronym: "UNEP",
    type: "un_agency",
    focusAreas: ["Environment", "Climate Change", "Ecosystems", "Waste Management"],
    address: "Regional Office, Dakar",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.unep.org",
    email: "unep-dakar@unep.org",
    programmes: ["Climate Adaptation", "Ecosystem Management", "Waste Management"],
    description: "UN agency for environmental protection and sustainable development.",
  },
  {
    id: "unops-regional",
    name: "UN Office for Project Services",
    acronym: "UNOPS",
    type: "un_agency",
    focusAreas: ["Infrastructure", "Procurement", "Project Management", "Capacity Building"],
    address: "Regional Office, Dakar",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.unops.org",
    email: "unops-dakar@unops.org",
    programmes: ["Infrastructure Development", "Sustainable Procurement", "Project Management Support"],
    description: "UN agency providing infrastructure, procurement, and project management services.",
  },
  {
    id: "unesco-dakar",
    name: "UNESCO Regional Office for West Africa",
    acronym: "UNESCO",
    type: "un_agency",
    focusAreas: ["Education", "Culture", "Science", "Communication", "Heritage"],
    address: "Dakar, Senegal",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.unesco.org",
    phone: "+221 33 859 2626",
    email: "dakar@unesco.org",
    description: "UN agency for education, science, culture, and communication.",
  },

  // ── Multilateral Development Banks ────────────────────────────────────────
  {
    id: "world-bank-gambia",
    name: "World Bank Group — Gambia",
    acronym: "World Bank",
    type: "multilateral_bank",
    focusAreas: ["Infrastructure", "Governance", "Digital Economy", "Social Protection", "Agriculture"],
    address: "Dakar, Senegal (covers Gambia)",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.worldbank.org/en/country/gambia",
    phone: "+221 33 859 5000",
    email: "gambia@worldbank.org",
    localRep: "Country Manager",
    fundingWindows: ["IDA", "Digital Economy for Africa (DE4A)", "Governance and Institutions"],
    programmes: ["Digital Transformation", "Agricultural Productivity", "Social Safety Nets"],
    description: "International financial institution providing loans and grants to developing countries.",
  },
  {
    id: "afdb-gambia",
    name: "African Development Bank — Gambia Country Office",
    acronym: "AfDB",
    type: "multilateral_bank",
    focusAreas: ["Infrastructure", "Agriculture", "Energy", "Private Sector", "Governance"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4545,
    lng: -16.5775,
    website: "https://www.afdb.org/en/countries/west-africa/gambia",
    phone: "+220 422 5678",
    email: "gambia@afdb.org",
    localRep: "Country Officer",
    fundingWindows: ["ADF", "Private Sector Facility", "Governance and Economic Reforms"],
    programmes: ["Agricultural Transformation", "Energy Access", "Private Sector Development"],
    description: "Africa's premier development finance institution.",
  },
  {
    id: "isdb-gambia",
    name: "Islamic Development Bank — Gambia Operations",
    acronym: "IsDB",
    type: "multilateral_bank",
    focusAreas: ["Infrastructure", "Agriculture", "Education", "Health", "SME Finance"],
    address: "Regional Hub, Dakar",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.isdb.org/gambia",
    email: "gambia@isdb.org",
    localRep: "Country Gateway Officer",
    fundingWindows: ["Islamic Development", "Public Sector", "Private Sector"],
    programmes: ["Infrastructure Development", "Human Capital Development", "SME Support"],
    description: "Multilateral development bank focused on Islamic finance and development.",
  },
  {
    id: "eib-gambia",
    name: "European Investment Bank — West Africa",
    acronym: "EIB",
    type: "multilateral_bank",
    focusAreas: ["Energy", "Infrastructure", "Private Sector", "Climate"],
    address: "Dakar, Senegal",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.eib.org",
    email: "eib-dakar@eib.org",
    programmes: ["Energy Infrastructure", "Climate Finance", "Private Sector Development"],
    description: "European Union's investment bank.",
  },
  {
    id: "ebid-gambia",
    name: "ECOWAS Bank for Investment and Development",
    acronym: "EBID",
    type: "multilateral_bank",
    focusAreas: ["Regional Integration", "Infrastructure", "Agriculture", "Trade Finance"],
    address: "Lome, Togo",
    area: "Regional",
    lat: 6.1256,
    lng: 1.2254,
    website: "https://www.ebid.org",
    email: "info@ebid.org",
    description: "ECOWAS development finance institution for regional integration.",
  },
  {
    id: "imf-gambia",
    name: "International Monetary Fund — Gambia",
    acronym: "IMF",
    type: "multilateral_bank",
    focusAreas: ["Macroeconomic Policy", "Fiscal Governance", "Capacity Building", "Debt Management"],
    address: "Dakar, Senegal (covers Gambia)",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.imf.org/en/countries/gmb",
    email: "imf-gambia@imf.org",
    programmes: ["Policy Advice", "Technical Assistance", "Capacity Building"],
    description: "International financial institution promoting global monetary cooperation.",
  },

  // ── Bilateral Donors ───────────────────────────────────────────────────────
  {
    id: "eu-delegation",
    name: "European Union Delegation to The Gambia",
    acronym: "EU",
    type: "bilateral_donor",
    focusAreas: ["Governance", "Sustainable Growth", "Job Creation", "Migration", "Digital Transformation", "Green Resilience"],
    address: "74 Atlantic Road, Fajara",
    area: "Fajara",
    lat: 13.4538,
    lng: -16.6782,
    website: "https://www.eeas.europa.eu/delegations/gambia",
    phone: "+220 449 5757",
    email: "delegation-gambia@eeas.europa.eu",
    localRep: "H.E. EU Ambassador",
    fundingWindows: ["European Development Fund", "NDICI – Global Europe", "EU Trust Fund for Africa"],
    programmes: ["Digital Transformation", "Youth Employment", "Good Governance", "Migration Management"],
    description: "Largest donor in The Gambia, representing all EU member states.",
  },
  {
    id: "giz-gambia",
    name: "Deutsche Gesellschaft für Internationale Zusammenarbeit",
    acronym: "GIZ",
    type: "bilateral_donor",
    focusAreas: ["Governance", "Energy", "Sustainable Economic Development", "Vocational Training"],
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4525,
    lng: -16.6790,
    website: "https://www.giz.de/en/worldwide/327.html",
    phone: "+220 449 5850",
    email: "giz-gambia@giz.de",
    localRep: "Country Director",
    programmes: ["Governance and Rule of Law", "Energy Efficiency", "Vocational Education and Training"],
    description: "German development agency implementing technical cooperation projects.",
  },
  {
    id: "fcdo-gambia",
    name: "British High Commission / FCDO Gambia",
    acronym: "FCDO",
    type: "bilateral_donor",
    focusAreas: ["Governance", "Rule of Law", "Security Sector Reform", "Human Capital Development", "Trade"],
    address: "48 Kairaba Avenue, Fajara",
    area: "Fajara",
    lat: 13.4525,
    lng: -16.6790,
    website: "https://www.gov.uk/world/organisations/british-high-commission-banjul",
    phone: "+220 449 5133",
    email: "ukin.gambia@fcdo.gov.uk",
    localRep: "British High Commissioner",
    programmes: ["Governance and Anti-Corruption", "Security Sector Reform", "Economic Development"],
    description: "UK's foreign ministry responsible for development assistance and diplomatic relations.",
  },
  {
    id: "afd-gambia",
    name: "Agence Française de Développement",
    acronym: "AFD",
    type: "bilateral_donor",
    focusAreas: ["Infrastructure", "Agriculture", "Governance", "Private Sector"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5770,
    website: "https://www.afd.fr/en/gambia",
    email: "afd-banjul@afd.fr",
    programmes: ["Sustainable Infrastructure", "Agricultural Development", "Private Sector Support"],
    description: "French development agency financing sustainable development projects.",
  },
  {
    id: "jica-gambia",
    name: "Japan International Cooperation Agency",
    acronym: "JICA",
    type: "bilateral_donor",
    focusAreas: ["Agriculture", "Food Security", "Infrastructure", "Health", "Education"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4545,
    lng: -16.5775,
    website: "https://www.jica.go.jp/gambia",
    email: "jica-gambia@jica.go.jp",
    localRep: "JICA Representative",
    programmes: ["Agricultural Development", "Fisheries", "Infrastructure Improvement"],
    description: "Japan's development agency providing technical cooperation and grant aid.",
  },
  {
    id: "usaid-gambia",
    name: "USAID West Africa (covers Gambia)",
    acronym: "USAID",
    type: "bilateral_donor",
    focusAreas: ["Health", "Agriculture", "Democracy", "Governance"],
    address: "Dakar, Senegal",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.usaid.gov/west-africa-regional",
    email: "usaid-wa@usaid.gov",
    programmes: ["Global Health", "Feed the Future", "Democracy and Governance"],
    description: "United States government's development agency.",
  },
  {
    id: "sida-gambia",
    name: "Swedish International Development Cooperation Agency",
    acronym: "SIDA",
    type: "bilateral_donor",
    focusAreas: ["Democracy", "Human Rights", "Environment", "Climate"],
    address: "Stockholm (covers Gambia via regional programmes)",
    area: "International",
    lat: 59.3293,
    lng: 18.0686,
    website: "https://www.sida.se",
    email: "sida@sida.se",
    programmes: ["Human Rights and Democracy", "Climate and Environment", "Peace and Security"],
    description: "Swedish government agency for international development cooperation.",
  },
  {
    id: "china-cooperation",
    name: "Embassy of China — Development Cooperation",
    acronym: "China",
    type: "bilateral_donor",
    focusAreas: ["Infrastructure", "Trade", "Investment", "Technology"],
    address: "Kombo Coastal Road, Bijilo",
    area: "Bijilo",
    lat: 13.4215,
    lng: -16.7295,
    website: "http://gm.china-embassy.gov.cn",
    phone: "+220 446 5311",
    email: "chinaemb_gm@mfa.gov.cn",
    programmes: ["Infrastructure Projects", "Trade and Investment", "Technology Transfer"],
    description: "Chinese embassy handling development cooperation and diplomatic relations.",
  },

  // ── Regional Bodies ────────────────────────────────────────────────────────
  {
    id: "ecowas-commission",
    name: "ECOWAS Commission — Gambia National Office",
    acronym: "ECOWAS",
    type: "regional_body",
    focusAreas: ["Regional Integration", "Economic Cooperation", "Trade", "Peace and Security"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4542,
    lng: -16.5768,
    website: "https://www.ecowas.int",
    phone: "+220 422 3455",
    email: "ecowas.gambia@ecowas.int",
    programmes: ["Regional Integration", "Trade Facilitation", "Peace and Security"],
    description: "Economic Community of West African States — regional political and economic union.",
  },
  {
    id: "ecreee",
    name: "ECOWAS Centre for Renewable Energy and Energy Efficiency",
    acronym: "ECREEE",
    type: "regional_body",
    focusAreas: ["Renewable Energy", "Energy Efficiency", "Sustainable Energy"],
    address: "Praia, Cape Verde",
    area: "Regional",
    lat: 14.9333,
    lng: -23.5125,
    website: "https://www.ecreee.org",
    email: "info@ecreee.org",
    programmes: ["Renewable Energy Policy", "Energy Efficiency", "Sustainable Energy Access"],
    description: "ECOWAS specialized agency for renewable energy and energy efficiency.",
  },
  {
    id: "erera",
    name: "ECOWAS Regional Electricity Regulatory Authority",
    acronym: "ERERA",
    type: "regional_body",
    focusAreas: ["Electricity Regulation", "Cross-border Energy Trade", "Regional Grid"],
    address: "Accra, Ghana",
    area: "Regional",
    lat: 5.6037,
    lng: -0.1870,
    website: "https://www.erera.arrec.org",
    email: "info@erera.arrec.org",
    programmes: ["Electricity Market Regulation", "Cross-border Trade Facilitation"],
    description: "ECOWAS agency responsible for electricity regulation in West Africa.",
  },

  // ── International NGOs ─────────────────────────────────────────────────────
  {
    id: "world-vision",
    name: "World Vision International — Gambia",
    acronym: "World Vision",
    type: "ingo",
    focusAreas: ["Child Protection", "Education", "Health", "WASH", "Food Security"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://www.wvi.org/gambia",
    email: "gambia@wvi.org",
    programmes: ["Child Protection", "Education", "Health and Nutrition", "WASH"],
    description: "Christian humanitarian organization focused on child well-being.",
  },
  {
    id: "care-gambia",
    name: "CARE International — Gambia",
    acronym: "CARE",
    type: "ingo",
    focusAreas: ["Humanitarian", "Women's Empowerment", "Food Security", "Resilience"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://www.care-international.org/gambia",
    email: "care.gambia@care.org",
    programmes: ["Women's Economic Empowerment", "Food Security", "Climate Resilience"],
    description: "Humanitarian organization fighting global poverty.",
  },
  {
    id: "actionaid-gambia",
    name: "ActionAid International — Gambia",
    acronym: "ActionAid",
    type: "ingo",
    focusAreas: ["Poverty Eradication", "Women's Rights", "Governance", "Climate Justice"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://actionaid.org/gambia",
    email: "gambia@actionaid.org",
    programmes: ["Women's Rights", "Climate Justice", "Democratic Governance"],
    description: "International NGO working against poverty and injustice.",
  },
  {
    id: "plan-international",
    name: "Plan International — Gambia",
    acronym: "Plan International",
    type: "ingo",
    focusAreas: ["Child Rights", "Education", "Protection", "Youth Empowerment"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://plan-international.org/gambia",
    email: "gambia@plan-international.org",
    programmes: ["Child Protection", "Quality Education", "Youth Economic Empowerment"],
    description: "Development and humanitarian organization advancing children's rights.",
  },
  {
    id: "save-children",
    name: "Save the Children — Gambia",
    acronym: "Save the Children",
    type: "ingo",
    focusAreas: ["Child Protection", "Education", "Health", "Nutrition"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://www.savethechildren.org/gambia",
    email: "gambia@savethechildren.org",
    programmes: ["Child Protection", "Education", "Health and Nutrition"],
    description: "International NGO promoting children's rights and well-being.",
  },
  {
    id: "red-cross",
    name: "Gambia Red Cross Society",
    acronym: "GRCS",
    type: "ingo",
    focusAreas: ["Humanitarian", "Disaster Response", "Health", "First Aid"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4550,
    lng: -16.5740,
    website: "https://www.redcross.gm",
    phone: "+220 422 8900",
    email: "info@redcross.gm",
    programmes: ["Disaster Management", "Health and Care", "Organizational Development"],
    description: "National Red Cross society providing humanitarian assistance.",
  },
  {
    id: "crs-gambia",
    name: "Catholic Relief Services — Gambia",
    acronym: "CRS",
    type: "ingo",
    focusAreas: ["Agriculture", "Health", "Microfinance", "Emergency Response"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://www.crs.org/gambia",
    email: "crs.gambia@crs.org",
    programmes: ["Agricultural Livelihoods", "Health", "Microfinance"],
    description: "International humanitarian agency of the Catholic Church.",
  },
  {
    id: "concern-worldwide",
    name: "Concern Worldwide — Gambia",
    acronym: "Concern",
    type: "ingo",
    focusAreas: ["Hunger", "Health", "Education", "Emergency Response"],
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5775,
    website: "https://www.concern.net/gambia",
    email: "gambia@concern.net",
    programmes: ["Hunger Reduction", "Health", "Education"],
    description: "International humanitarian organization fighting hunger and poverty.",
  },
  {
    id: "oxfam-gambia",
    name: "Oxfam — Gambia",
    acronym: "Oxfam",
    type: "ingo",
    focusAreas: ["Economic Justice", "Gender Equality", "Climate", "Humanitarian"],
    address: "Dakar, Senegal (covers Gambia)",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.oxfam.org/en/what-we-do/countries/gambia",
    email: "oxfam-gambia@oxfam.org",
    programmes: ["Economic Justice", "Gender Justice", "Climate Action"],
    description: "Confederation of NGOs fighting inequality and poverty.",
  },
  {
    id: "msf-gambia",
    name: "Doctors Without Borders (MSF) — Gambia",
    acronym: "MSF",
    type: "ingo",
    focusAreas: ["Health", "Medical Humanitarian", "Emergency Response"],
    address: "Dakar, Senegal (covers Gambia)",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.msf.org/gambia",
    email: "msf-dakar@msf.org",
    programmes: ["Emergency Medical Care", "Health Systems Strengthening"],
    description: "International medical humanitarian organization.",
  },

  // ── Foundations ────────────────────────────────────────────────────────────
  {
    id: "gates-foundation",
    name: "Bill & Melinda Gates Foundation — West Africa",
    acronym: "Gates Foundation",
    type: "foundation",
    focusAreas: ["Health", "Agriculture", "Digital Financial Services"],
    address: "Regional Office, Dakar",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.gatesfoundation.org",
    email: "info@gatesfoundation.org",
    fundingWindows: ["Global Health", "Agricultural Development", "Digital Financial Inclusion"],
    programmes: ["Polio Eradication", "Agricultural Productivity", "Digital Finance"],
    description: "World's largest private philanthropic foundation.",
  },
  {
    id: "open-society",
    name: "Open Society Foundations — West Africa",
    acronym: "OSF",
    type: "foundation",
    focusAreas: ["Justice", "Governance", "Digital Rights", "Human Rights"],
    address: "Dakar, Senegal",
    area: "Regional",
    lat: 14.6937,
    lng: -17.4441,
    website: "https://www.opensocietyfoundations.org",
    email: "osf-dakar@opensociety.org",
    fundingWindows: ["Justice and Governance", "Digital Rights", "Human Rights"],
    programmes: ["Rule of Law", "Access to Justice", "Digital Freedom"],
    description: "Philanthropic organization advancing justice, governance, and human rights.",
  },
  {
    id: "mastercard-foundation",
    name: "Mastercard Foundation — West Africa",
    acronym: "Mastercard Foundation",
    type: "foundation",
    focusAreas: ["Education", "Youth Employment", "Digital Inclusion"],
    address: "Accra, Ghana",
    area: "Regional",
    lat: 5.6037,
    lng: -0.1870,
    website: "https://mastercardfdn.org",
    email: "info@mastercardfdn.org",
    fundingWindows: ["Young Africa Works", "Scholarships", "Digital Inclusion"],
    programmes: ["Youth Employment", "Digital Skills", "Secondary Education"],
    description: "Philanthropic foundation focused on education and youth employment.",
  },
  {
    id: "ford-foundation",
    name: "Ford Foundation — West Africa",
    acronym: "Ford Foundation",
    type: "foundation",
    focusAreas: ["Social Justice", "Governance", "Creative Expression"],
    address: "Lagos, Nigeria",
    area: "Regional",
    lat: 6.5244,
    lng: 3.3792,
    website: "https://www.fordfoundation.org",
    email: "westafrica@fordfoundation.org",
    fundingWindows: ["Gender and Racial Justice", "Governance and Citizenship", "Creative Freedom"],
    programmes: ["Social Justice", "Democratic Governance", "Art and Culture"],
    description: "Philanthropic foundation promoting social justice and democratic values.",
  },
  {
    id: "rockefeller-foundation",
    name: "Rockefeller Foundation — Africa",
    acronym: "Rockefeller",
    type: "foundation",
    focusAreas: ["Health", "Climate", "Economic Opportunity"],
    address: "Nairobi, Kenya",
    area: "Regional",
    lat: -1.2864,
    lng: 36.8172,
    website: "https://www.rockefellerfoundation.org",
    email: "africa@rockfound.org",
    programmes: ["Health", "Climate and Resilience", "Economic Opportunity"],
    description: "Philanthropic foundation focused on health, climate, and economic opportunity.",
  },
];

// ── Helper functions ──────────────────────────────────────────────────────────

export function getPartnersByType(type: DevelopmentPartner["type"]): DevelopmentPartner[] {
  return DEVELOPMENT_PARTNERS.filter(p => p.type === type);
}

export function searchPartners(query: string): DevelopmentPartner[] {
  const q = query.toLowerCase();
  return DEVELOPMENT_PARTNERS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.acronym.toLowerCase().includes(q) ||
    p.focusAreas.some(f => f.toLowerCase().includes(q)) ||
    (p.description?.toLowerCase().includes(q) ?? false)
  );
}

export function getStreetViewUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/place/${lat},${lng}/@${lat},${lng},17z/data=!3m1!1e3`;
}

export function getDirectionsUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/dir//${lat},${lng}`;
}

export function getMapEmbedUrl(lat: number, lng: number): string {
  return `https://maps.google.com/maps?q=${lat},${lng}&z=16&output=embed`;
}
