export interface EmbassyLocation {
  id: string;
  name: string;
  country: string;
  type: "embassy" | "high_commission" | "consulate" | "international_agency" | "honorary_consulate";
  address: string;
  area: string;
  lat: number;
  lng: number;
  phone: string;
  email?: string;
  website: string;
  hours?: string;
  services?: string[];
  emergencyContact?: string;
}

export const EMBASSY_LOCATIONS: EmbassyLocation[] = [
  // ── Resident Embassies & High Commissions ──────────────────────────────────
  {
    id: "us-embassy",
    name: "United States Embassy",
    country: "United States of America",
    type: "embassy",
    address: "Kairaba Avenue, Fajara",
    area: "Fajara",
    lat: 13.4528,
    lng: -16.6785,
    phone: "+220 439 2856",
    email: "ConsularBanjul@state.gov",
    website: "https://gm.usembassy.gov",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["Visa Services", "US Citizen Services", "Emergency Assistance"],
    emergencyContact: "+220 439 2856 (after hours)",
  },
  {
    id: "china-embassy",
    name: "Embassy of the People's Republic of China",
    country: "China",
    type: "embassy",
    address: "Kombo Coastal Road, Bijilo TDA",
    area: "Bijilo",
    lat: 13.4215,
    lng: -16.7295,
    phone: "+220 446 5311",
    email: "chinaemb_gm@mfa.gov.cn",
    website: "http://gm.china-embassy.gov.cn",
    hours: "Mon–Fri, 9:00 AM – 12:00 PM, 2:30 – 5:00 PM",
    services: ["Visa Services", "Chinese Citizen Services", "Notarial Services"],
  },
  {
    id: "uk-high-commission",
    name: "British High Commission",
    country: "United Kingdom",
    type: "high_commission",
    address: "48 Kairaba Avenue, Fajara",
    area: "Fajara",
    lat: 13.4525,
    lng: -16.6790,
    phone: "+220 449 5133",
    email: "ukin.gambia@fcdo.gov.uk",
    website: "https://www.gov.uk/world/organisations/british-high-commission-banjul",
    hours: "Mon–Thu, 8:30 AM – 4:30 PM; Fri 8:30 AM – 1:00 PM",
    services: ["UK Citizen Services", "Emergency Travel Documents", "Notarial Services"],
    emergencyContact: "+220 449 5133",
  },
  {
    id: "nigeria-high-commission",
    name: "Nigeria High Commission",
    country: "Nigeria",
    type: "high_commission",
    address: "48 Mamadi Maniyang Highway, Fajara",
    area: "Fajara",
    lat: 13.4530,
    lng: -16.6780,
    phone: "+220 449 5560",
    email: "info@nigeriahcbanjul.com",
    website: "https://www.nigeriahcbanjul.com",
    hours: "Mon–Fri, 9:00 AM – 4:00 PM",
    services: ["Passport Services", "Visa Services", "Nigerian Citizen Services"],
  },
  {
    id: "senegal-embassy",
    name: "Embassy of Senegal",
    country: "Senegal",
    type: "embassy",
    address: "Atlantic Road, Fajara",
    area: "Fajara",
    lat: 13.4535,
    lng: -16.6775,
    phone: "+220 449 5210",
    email: "ambasenegal@qanet.gm",
    website: "https://www.ambasenegal.gm",
    hours: "Mon–Fri, 9:00 AM – 4:00 PM",
    services: ["Visa Services", "Senegalese Citizen Services"],
  },
  {
    id: "turkey-embassy",
    name: "Embassy of Turkey",
    country: "Turkey",
    type: "embassy",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4520,
    lng: -16.6788,
    phone: "+220 449 5850",
    email: "embassy.banjul@mfa.gov.tr",
    website: "http://banjul.emb.mfa.gov.tr",
    hours: "Mon–Fri, 9:00 AM – 5:00 PM",
    services: ["Visa Services", "Turkish Citizen Services"],
  },
  {
    id: "morocco-embassy",
    name: "Embassy of Morocco",
    country: "Morocco",
    type: "embassy",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4522,
    lng: -16.6782,
    phone: "+220 449 5230",
    email: "sifmabanjul@maec.gov.ma",
    website: "https://www.embassyofmorocco.gm",
    hours: "Mon–Fri, 9:00 AM – 4:00 PM",
    services: ["Visa Services", "Moroccan Citizen Services"],
  },
  {
    id: "cuba-embassy",
    name: "Embassy of Cuba",
    country: "Cuba",
    type: "embassy",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4526,
    lng: -16.6778,
    phone: "+220 449 5440",
    email: "embacuba@qanet.gm",
    website: "https://misiones.minrex.gob.cu/es/gambia",
    hours: "Mon–Fri, 9:00 AM – 3:00 PM",
    services: ["Visa Services", "Cuban Citizen Services"],
  },
  {
    id: "libya-embassy",
    name: "Embassy of Libya",
    country: "Libya",
    type: "embassy",
    address: "Banjul",
    area: "Banjul",
    lat: 13.4550,
    lng: -16.5750,
    phone: "+220 422 7890",
    website: "https://www.embassyoflibya.gm",
    hours: "Mon–Thu, 9:00 AM – 3:00 PM",
    services: ["Visa Services", "Libyan Citizen Services"],
  },
  {
    id: "india-honorary",
    name: "Honorary Consulate of India",
    country: "India",
    type: "honorary_consulate",
    address: "Banjul",
    area: "Banjul",
    lat: 13.4540,
    lng: -16.5780,
    phone: "+220 422 7891",
    email: "hcibanjul@mea.gov.in",
    website: "https://www.hcindia-ban.gm",
    hours: "Mon–Fri, 10:00 AM – 1:00 PM",
    services: ["Passport Services", "Visa Services", "Indian Citizen Registration"],
  },
  {
    id: "austria-honorary",
    name: "Honorary Consulate of Austria",
    country: "Austria",
    type: "honorary_consulate",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4515,
    lng: -16.6795,
    phone: "+220 449 5678",
    email: "austria.consulate@qanet.gm",
    website: "https://www.bmeia.gv.at/en/austrian-embassy-dakar",
    hours: "By appointment only",
    services: ["Limited consular services", "Emergency assistance"],
  },
  {
    id: "belgium-honorary",
    name: "Honorary Consulate of Belgium",
    country: "Belgium",
    type: "honorary_consulate",
    address: "Bakau, Banjul",
    area: "Bakau",
    lat: 13.4785,
    lng: -16.6725,
    phone: "+220 449 5890",
    email: "belgium.consulate@qanet.gm",
    website: "https://belgium.diplomatie.gm",
    hours: "By appointment only",
    services: ["Emergency passport services", "Notarial services"],
  },
  // ── International Organizations ───────────────────────────────────────────
  {
    id: "eu-delegation",
    name: "European Union Delegation",
    country: "European Union",
    type: "international_agency",
    address: "74 Atlantic Road, Fajara",
    area: "Fajara",
    lat: 13.4538,
    lng: -16.6782,
    phone: "+220 449 5757",
    email: "delegation-gambia@eeas.europa.eu",
    website: "https://www.eeas.europa.eu/delegations/gambia",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["EU Cooperation", "Trade & Development", "Political Affairs"],
  },
  {
    id: "undp-gambia",
    name: "UNDP Gambia",
    country: "United Nations",
    type: "international_agency",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4523,
    lng: -16.6792,
    phone: "+220 449 5555",
    email: "registry.gm@undp.org",
    website: "https://www.undp.org/gambia",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["Development Programs", "SDG Implementation"],
  },
  {
    id: "unicef-gambia",
    name: "UNICEF Gambia",
    country: "United Nations",
    type: "international_agency",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4525,
    lng: -16.6790,
    phone: "+220 449 5454",
    email: "banjul@unicef.org",
    website: "https://www.unicef.org/gambia",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["Child Protection", "Education", "Health Programs"],
  },
  {
    id: "who-gambia",
    name: "World Health Organization (WHO) Gambia",
    country: "United Nations",
    type: "international_agency",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4520,
    lng: -16.6795,
    phone: "+220 449 5656",
    email: "afwogm@who.int",
    website: "https://www.afro.who.int/countries/gambia",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["Public Health", "Disease Prevention"],
  },
  {
    id: "iom-gambia",
    name: "IOM — International Organization for Migration",
    country: "United Nations",
    type: "international_agency",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4522,
    lng: -16.6788,
    phone: "+220 449 5455",
    email: "iombanjul@iom.int",
    website: "https://www.iom.int/countries/gambia",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["Migration Management", "Border Management", "Assisted Voluntary Return"],
  },
  {
    id: "wfp-gambia",
    name: "World Food Programme (WFP) Gambia",
    country: "United Nations",
    type: "international_agency",
    address: "Fajara, Banjul",
    area: "Fajara",
    lat: 13.4524,
    lng: -16.6793,
    phone: "+220 449 5353",
    email: "wfp.gambia@wfp.org",
    website: "https://www.wfp.org/countries/gambia",
    hours: "Mon–Fri, 8:30 AM – 5:00 PM",
    services: ["Food Security", "Nutrition Programs", "Emergency Food Assistance"],
  },
  {
    id: "ecowas-gambia",
    name: "ECOWAS National Office Gambia",
    country: "ECOWAS",
    type: "international_agency",
    address: "Banjul",
    area: "Banjul",
    lat: 13.4542,
    lng: -16.5768,
    phone: "+220 422 3455",
    email: "ecowas.gambia@ecowas.int",
    website: "https://www.ecowas.int",
    hours: "Mon–Fri, 9:00 AM – 4:00 PM",
    services: ["Regional Integration", "Economic Cooperation"],
  },
  {
    id: "mofa-gambia",
    name: "Ministry of Foreign Affairs",
    country: "Gambia",
    type: "international_agency",
    address: "Banjul",
    area: "Banjul",
    lat: 13.4545,
    lng: -16.5770,
    phone: "+220 422 3578",
    email: "info@mofa.gov.gm",
    website: "https://www.mofa.gov.gm",
    hours: "Mon–Fri, 9:00 AM – 4:30 PM",
    services: ["Diplomatic Relations", "Foreign Affairs", "Consular Services"],
  },
];

export function getEmbassiesByType(type: EmbassyLocation["type"]): EmbassyLocation[] {
  return EMBASSY_LOCATIONS.filter(loc => loc.type === type);
}

export function searchEmbassies(query: string): EmbassyLocation[] {
  const q = query.toLowerCase();
  return EMBASSY_LOCATIONS.filter(loc =>
    loc.name.toLowerCase().includes(q) ||
    loc.country.toLowerCase().includes(q) ||
    loc.address.toLowerCase().includes(q) ||
    loc.area.toLowerCase().includes(q)
  );
}

export function getStreetViewUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/place/${lat},${lng}/@${lat},${lng},17z/data=!3m1!1e3`;
}

export function getDirectionsUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/dir//${lat},${lng}`;
}

export function getMapEmbedUrl(lat: number, lng: number): string {
  return `https://maps.google.com/maps?q=${lat},${lng}&z=16&output=embed`;
}
